Gregable/social-security-tools

partials/benefit-estimate.html, src/constants.js, src/tax-engine.js
It's not a fixed per-year rate, it varies before and after the 3 year mark.
Issue #11
=> Fix calculation for early benefit reduction.

partials/benefit-estimate.html, src/ssa-parse.js, stylesheet.css
Apparently in some browser contexts, this is still not splitting exactly correctly. https://github.com/Gregable/social-security-tools/issues/15
=> Force the month picker to split over 2 sets of 6 months each. 

partials/benefit-estimate.html, partials/ssa-earnings-table.html, src/ssa.js, src/tax-engine.js, stylesheet.css
https://github.com/Gregable/social-security-tools/issues/13
https://github.com/Gregable/social-security-tools/issues/8
=> Several fixes

src/ssa.js, src/tax-engine.js
=> No longer treat future year's calculation as top 35 if they are $0. Also make the slider not allow $0

src/ssa.js
Slider should top out at max earnings for current year (not previous year)
=> Use current year's max earnings in slider

src/constants.js
Added new maximum earnings, tax rates, wage indices, and cola adjustment numbers.
=> Updating with 2018 constants.

src/constants.js
Looks like ssa.gov does this early!
=> Update current year to 2019.

partials/eligibility.html, partials/ssa-earnings-table.html, src/recipient.js, src/ssa.js
=> Fix the top 35 calculation with respect to ties.

partials/benefit-estimate.html, partials/birthdate.html, partials/eligibility.html, partials/filing-date.html, partials/frequent-questions.html, partials/primary-insurance-amount.html, partials/spousal-benefit.html, partials/ssa-earnings-table.html, stylesheet.css
=> Fix offsets with respect to the future earnings slider bar.

debug-user-paste.html
trouble pasting data into the tool.
=> Add a small debug tool that I can point users to if they are having

partials/navbar.html, partials/paste-prompt.html, src/ssa.js
Make the pasteprompt placeholder a constant.
=> Move the navbar to it's own controller.

calculator.html, index.html, partials/eligibility.html, partials/ssa-earnings-table.html, src/birthday.js, src/recipient.js, src/spec/javascripts/birthday_spec.js, src/spec/javascripts/recipient_spec.js, src/spec/javascripts/support/jasmine.yml, src/ssa.js
=> Break out birthday computations into a separate library.

guide/maximum.html, tools/deploy.py
Fix maximum calculation.
Use new boto3 library for s3 upload, tinys3 no longer seems to work.
=> Max and boto3

about.html, src/constants.js
Add a "last updated" date to the about page.
Addresses https://github.com/Gregable/social-security-tools/issues/93
=> Update constants for 2019/2020.

src/constants.js, src/recipient.js, src/ssa-parse.js
Fixes https://github.com/Gregable/social-security-tools/issues/91
=> Allow user to paste data in years later than the current year.

src/recipient.js
Fixes https://github.com/Gregable/social-security-tools/issues/130
=> Fix bug with top35 years getting incorrectly shown in the future years table.

partials/eligibility.html
Fixes https://github.com/Gregable/social-security-tools/issues/121
=> Improve the language around the required credits.

src/spousal-chart.js
Fixes https://github.com/Gregable/social-security-tools/issues/120
=> Fix issue where spousal chart doesn't update on future earnings slider if mouse toggled in the clicked state.

src/ssa.js, src/utils.js
provide much value in the place it was used (setting a maximum on the
spousal PIA input box).
=> Remove the maximum PIA calculation. It was incorrect, and didn't

about.html, calculator.html, contact.html, contributors.html, guide/inflation.html, guide/maximum.html, guides.html, index.html, partials/benefit-estimate.html, partials/eligibility.html, partials/filing-date.html, partials/header.html, partials/navbar.html, partials/paste-prompt.html, partials/primary-insurance-amount.html, partials/spousal-benefit.html, partials/ssa-earnings-table.html, src/age-chart.js, src/breakpoint-chart.js, src/recipient.js, src/ssa.js, stylesheet.css, youngpaste.txt
Improved layout for devices with narrow screen widths and print formatting.
=> Mobile and Print

partials/age-request.html, partials/spousal-benefit.html, src/ssa.js, src/utils.js
=> Fix date entry on browsers without a native date input type. 

guide/maximum.js
=> Update maximum benefit to consider spousal at 1/2 of maximum at NRA, not

src/spousal-chart.mjs
Also replace `var` with `let`.
=> Quick fix to spousal chart.

calculator.html, index.html
=> Get rid of some console errors on root page. Don't hurt anything, but

about.html, calculator.html, contact.html, contributors.html, guide/inflation.html, guide/maximum.html, guides.html, index.html, partials/header.html, robots.txt, sitemap.xml
by search engines. Meta descriptions, schema.org annotations, etc.
=> Bunch of random small tweaks to make some of the pages easier to find

partials/spousal-benefit.html
=> Fix the spousal benefit reduction per year.

guide/feed.rss, guide/international-agreements.html, guides.html, partials/eligibility.html
=> Add a short guide with more details on the international agreements.

partials/paste-prompt.html
=> Update the text describing how to retrieve one's earnings record.

partials/benefit-estimate.html
=> Improve text wrapping in the early retirement case.

src/stylesheet.css
Previously, h3 was left of h2, which looked odd.
=> unify padding on headers.

src/components/PasteFlow.svelte, src/lib/recipient.ts, src/test/recipient.test.ts
This method follows the Svelte store contract, and returns an unsubscribe function.
Also updated minor comments in PasteFlow.svelte.
=> Add a subscribe method to the recipient class.

package-lock.json, src/components/EarningsTable.svelte, src/components/PasteFlow.svelte, src/components/PastePrompt.svelte, src/components/Report.svelte, src/components/Slider.svelte, src/lib/context.ts, src/stories/EarningsTable.stories.ts, src/stories/Slider.stories.ts
EarningsTable in progress, but incomplete.
=> Added a Slider component to support the EarningsTable.

src/App.svelte, src/components/EarningsFlow.svelte, src/components/EarningsTable.svelte, src/components/FutureEarningsSliders.svelte, src/components/PastePrompt.svelte, src/components/Slider.svelte, src/lib/earning-record.ts, src/lib/month-time.ts, src/lib/ssa-parse.ts, src/stories/EarningsFlow.stories.ts, src/stories/EarningsTable.stories.ts, src/stories/FutureEarningsSliders.stories.ts, src/stories/Slider.stories.ts, src/test/ssa-parse.test.ts
Layout is still a little messed up.
=> Earnings Record Report added to the App

src/App.svelte, src/components/EarningsReport.svelte, src/components/EligibilityReport.svelte, src/components/EligibilityTable.svelte, src/components/Expando.svelte, src/lib/earning-record.ts, src/lib/recipient.ts, src/stories/EligibilityReport.stories.ts, src/stories/EligibilityTable.stories.ts, src/stories/Expando.demo.svelte, src/stories/Expando.stories.ts, src/test/recipient.test.ts
Supporting work adding EligibilityTable and Expando components.
Minor changes to some of the earnings report components to match the new EligibilityReport's interface.
=> Add EligibilityReport.

src/App.svelte, src/components/EligibilityReport.svelte, src/components/Expando.svelte, src/components/Sidebar.svelte
Still to be implemented is an IntersectionObserver based system to highlight the current section in the sidebar.
=> Add a sidebar to the report.

src/App.svelte, src/components/Expando.svelte, src/components/Sidebar.svelte, src/components/SidebarSection.svelte, src/lib/ssa-parse.ts
The sidebar uses IntersectionObserver to detect when each section is visible, and highlights the corresponding section in the sidebar.
=> Implement a sidebar component.

src/App.svelte, src/components/DemoData.svelte, src/components/EligibilityReport.svelte, src/components/FilingDateChart.svelte, src/components/FilingDateReport.svelte, src/components/FutureEarningsSliders.svelte, src/components/NormalRetirementAgeReport.svelte, src/components/PasteFlow.svelte, src/components/PiaReport.svelte, src/components/RecipientName.svelte, src/components/SpouseQuestion.svelte, src/lib/recipient.ts, src/stories/EarningsReport.stories.ts, src/stories/EligibilityReport.stories.ts, src/stories/Expando.stories.ts, src/stories/FilingDateChart.stories.ts, src/stories/FilingDateReport.stories.ts, src/stories/FutureEarningsSliders.stories.ts, src/stories/Header.stories.ts, src/stories/NormalRetirementAgeReport.stories.ts, src/stories/PiaReport.stories.ts, src/stories/RecipientName.demo.svelte, src/stories/RecipientName.stories.ts, src/stories/Slider.stories.ts, src/test/recipient.test.ts
This allows us to insert the name of the recipient into the report in different places. The recipient will also be styled differently if it is the first user or the second user.
If there is only one user, then the name will be presented as "you", "your", etc as defined by the report. These variants are not styled.
In this way, the reports are clear as to which user is being described.
=> RecipientName component.

about.html, src/App.svelte, src/components/BendpointChart.svelte, src/components/CombinedChart.svelte, src/components/EarningsReport.svelte, src/components/EarningsTable.svelte, src/components/EligibilityReport.svelte, src/components/EligibilityTable.svelte, src/components/Expando.svelte, src/components/FilingDateChart.svelte, src/components/PiaReport.svelte, src/components/Sidebar.svelte, src/components/SpousalBenefit.svelte, src/stories/FullReport.stories.ts
Attempt to make all of the components work down to small mobile screen widths. The combined chart still doesn't fit on the smallest of screens but now there is a warning suggesting the user rotate the device.
=> Responsive focus changes.

src/lib/components/FilingDateChart.svelte
than the future sliders in a wide screen situation.
=> Ensure that the filing date chart doesn't go wider

src/lib/components/BendpointChart.svelte, src/lib/components/CombinedChart.svelte, src/lib/components/FilingDateChart.svelte, src/lib/components/Slider.svelte
Charts and Sliders were not working properly for move events triggered on a touchscreen device. This should resolve that issue.
=> Fix issues with pointer interactions.

src/lib/components/CombinedChart.svelte, src/lib/components/EarningsReport.svelte, src/lib/components/EarningsTable.svelte, src/lib/components/EligibilityReport.svelte, src/lib/components/EligibilityTable.svelte, src/lib/components/Expando.svelte, src/lib/components/IndexedEarningsReport.svelte, src/lib/components/IndexedEarningsTable.svelte, src/lib/components/NormalRetirementAgeReport.svelte, src/lib/components/PiaReport.svelte, src/lib/components/Sidebar.svelte, src/lib/global.css, src/routes/+page.svelte, src/routes/calculator/+page.svelte
- They no longer jitter if the contents expand while closed.
- Print views correctly calculate height when open or closed.
=> Fix expandos issues:

src/lib/components/MoreResources.svelte, src/lib/components/Sidebar.svelte, src/routes/calculator/+page.svelte
This way sidebar navigation isn't lost on back button.
=> Add pushstate events.

src/lib/components/PasteFlow.svelte
URL string looks like:
```
/calculator#pia1=3000&dob1=1965-09-21&name1=Alex
/calculator#pia1=3000&dob1=1965-09-21&name1=Alex&pia2=500&dob2=1962-09-28&name2=Chris
```
Date of birth is YYYY-MM-DD.
=> Support parameter based entry:

src/lib/components/AgeRequest.svelte, src/lib/components/FilingDateReport.svelte, src/lib/components/PasteFlow.svelte, src/lib/components/PiaReport.svelte, src/lib/components/Sidebar.svelte, src/routes/calculator/+page.svelte
Also displays the user entered PIA in the report.
Fixes #286
=> Fixes issues with entering a zero PIA.

src/lib/components/CombinedChart.svelte, src/lib/components/FilingDateReport.svelte, src/lib/components/PiaReport.svelte, src/lib/components/SpousalBenefit.svelte, src/lib/pia.ts, src/lib/recipient.ts
=> Reduce the PIA to $0 for ineligible recipients.

src/lib/components/CombinedChart.svelte
=> Add a link to Open Social Security.

src/lib/components/BendpointChart.svelte, src/lib/components/FutureEarningsSliders.svelte, src/lib/constants.ts, src/lib/earning-record.ts, src/lib/recipient.ts, src/test/earning-record.test.ts, src/test/pia.test.ts
309 fixed the cap on the input side, but not on the indexing side. This fixes the latter and makes a few other related changes.
=> Fix Capped Income.

src/routes/+layout.ts, vercel.json
https://posthog.com/docs/advanced/proxy/vercel
=> Use vercel rewrites as a reverse proxy for posthog

src/routes/guides/delayed-january-bump/+page.svelte
Typical FRA is not clear as it depends on age.
=> Fix possible confusing comment.

src/lib/components/Expando.svelte
fixes https://github.com/Gregable/social-security-tools/issues/354
I'm pretty new to svelte so let me know if there's a different way you'd like me to do this. love the project by the way, thanks for creating it!
=> set max height on expando if initiallyExpanded

src/lib/components/AgeRequest.svelte
A few minor quality of life improvements for the DOB entry form:
- autofocus the first input box when it loads so the user doesn't have to click into it
- when a given box is filled in, automatically move the cursor to the next box
- allow the `enter` key to submit the form when all boxes are filled in and form is valid
=> Easier age form

src/routes/strategy/+page.svelte, src/routes/strategy/components/DiscountRateInput.svelte, src/routes/strategy/components/RecipientInputs.svelte
Applies a standardized input styling to `DiscountRateInput` and `RecipientInputs` components, improving visual consistency and user experience. This includes updated padding, border, border-radius, and focus styles.
=> Refactor: Apply consistent input styling
