Gregable/social-security-tools

src/ssa-parse.js

the pasted table in a more browser-neutral manner.

Firefox copies a table in a different manner than Chrome. Parse

---

app.html
partials/age-request.html
partials/benefit-estimate.html
partials/paste-confirm.html
partials/paste-prompt.html
partials/ssa-earnings-table.html
src/ssa.js
stylesheet.css

Request user's age before displaying the report, rather than introducing the age picker inline in the report before explaining normal retirement age. This affects the PIA calculation for users nearing retirement.
Addresses #27

Request user's age before displaying the report

---

app.html
partials/benefit-estimate.html
partials/eligibility.html
partials/filing-date.html
partials/navbar.html
partials/primary-insurance-amount.html
partials/spousal-benefit.html
src/constants.js
src/recipient.js
stylesheet.css

First cut at credits.  
Credits are an important aspect of social security retirement benefits, as the second demo example doesn't earn the required 40 credits and their PIA is actually 0.
It doesn't zero out PIA calculations if you are not eligible.  I wanted to discuss with you what should be shown in the PIA and subsequent sections when the recipient is not eligible.  Should it just show PIA = 0?  Should it show the current calculations and then an override to 0 with a reference back to the eligibility section?

Implement Eligibility Credits

---

src/spec/javascripts/ssa-parse_spec.js
src/spec/javascripts/support/jasmine.yml
src/ssa-parse.js

dealing with trailing whitespace in the pasted contents.

Add tests for parsing SSA dumps. Fix a user-reported parse failure case

---

index.html

Add disableRemotePlayback attributes to the video tags on the root
page. This fixes an issue where you might see a chromecast icon prompt
in the corner of some of the videos.

Add disableRemotePlayback attributes

---

guides.html

Just noticed that the link from the guides page to the about page didn't work

Fix link to the about page from the guides page

---

about.html
partials/primary-insurance-amount.html
src/constants.mjs
src/ssa.mjs

This update includes constants for 2022, such as updated COLA and wage indices.
A number of people have asked why the site doesn't display 2021 COLA increases, probably because the increase was so significant this year. I haven't displayed COLAs until they come into effect, which isn't until Jan 1, 2022. This is confusing though and leads people to believe the site isn't updated. So, I've added a line to the list of COLAs that displays the future COLA number if we have it, but shows it in a different format and calls out that it won't be applied until the following year.

2022 Constants

---

about.html
calculator.html
contact.html
contributors.html
guide/covid-awi-drop.html
guide/earnings-cap.html
guide/indexing-factors.html
guide/inflation.html
guide/maximum.html
guides.html
index.html
src/analytics.mjs

This doesn't reveal anything about the user, only about the loading
performance (how fast the page loads).

Add Google Analytics reporting for Signed HTTP Exchange Web Vitals data.

---

partials/benefit-estimate.html
partials/navbar.html
partials/primary-insurance-amount.html
src/stylesheet.css

- Make the final PIA text larger and more visible in the text for easy copy / paste into other tools.
- Tweak the text around the reduction / increase in benefits for delayed / early retirement. Previously it could be misunderstood to be an effect that only occurs on year boundaries. Make it clearer that this is a monthly adjustment.
-  Tweak some CSS styles and text so that a few of the clickable navigation headers now fit on one line for most browsers.

Visual / Text tweaks

---

guide/federal-taxes.html

security. On narrow screens (mobile), four colums don't fit well. By increasing the column height, the list becomes 3 columns.

Change the column height on the list of states that don't tax social

---

src/ssa-parse.mjs

User reported an input format that used `$-` to represent zero values, which were generating NaN errors that were not caught correctly. These are now being parsed correctly as $0.

Improve the ssa-parse.mjs method.

---

src/App.svelte
src/components/EarningsReport.svelte
src/components/EligibilityReport.svelte

With two users, the colors on names gets a little busy.
This change removes the username headers, instead folding them into the heading for the "Earnings Record", and removing the color.
This also removes the green color from the big "Eligible" text, though the red is still maintained for ineligibile users.
Overall, this makes the page a little less busy, and a little more readable.

Reduce the amount of color.

---

src/lib/components/FutureEarningsSliders.svelte
src/lib/earning-record.ts
src/lib/recipient.ts
src/stories/FutureEarningsSliders.stories.ts

Fixes #113.
By default, ssa.gov assumes the user will continue earning the same as the previous year's earnings until and including the year of normal retirement age. We want to set the sliders to the same initial value so we get the same "answer".

Match ssa.gov more closely.

---

src/lib/components/PasteFlow.svelte

This tracks the following events:
- Clicked a "load demo" link, but not which one.
- Successfully pasted data for a single user, but not the data.
- Successfully pasted data for a user and spouse, but not the data.
In none of these cases are we tracking anything sensitive, such as income, name, birthdate, etc.

Add basic analytics event tracking.

---

src/lib/components/CombinedHeading.svelte
src/lib/components/FutureEarningsSliders.svelte
src/lib/components/Sidebar.svelte
src/lib/components/SidebarSection.svelte
src/lib/context.ts
src/routes/calculator/+page.svelte

The scrolling behavior in the sidebar interacts with the sticky elements of the filing date sliders. This commit fixes the issue so that the user sees the sidebar highlight the correct section when scrolling and scroll to the correct point when clicking on a section.

Fix sidebar scrolling behavior.

---

src/lib/components/AgeRequest.svelte
src/lib/components/DemoData.svelte
src/lib/components/PasteConfirm.svelte
src/lib/components/PasteFlow.svelte
src/lib/components/PastePrompt.svelte

Main change is the date picker. 
The browser native <input type=date> box has a poor mobile UX for picking non-recent dates.
It appears that the only affordance for navigating backwards from the current month is one month per tap. For someone in their 60s looking at retirement, that would indeed be hundreds of taps to select their birthday.
I went with https://design-system.service.gov.uk/patterns/dates/#asking-for-memorable-dates after swapping month / day for a US audience:

Improve the data entry

---

src/routes/guides/spousal-benefit-filing-date/+page.svelte

Svelte doesn't like the relative links to anchor elements.

Fix release.

---

src/lib/components/CombinedChart.svelte
src/lib/components/EligibilityReport.svelte
src/lib/components/FilingDateChart.svelte
src/lib/components/FilingDateReport.svelte
src/lib/components/FutureEarningsSliders.svelte
src/lib/components/IndexedEarningsReport.svelte
src/lib/components/NormalRetirementAgeReport.svelte
src/lib/components/PiaReport.svelte
src/lib/components/RecipientName.svelte
src/lib/components/SpousalBenefit.svelte
src/lib/components/SpousalReport.svelte

Now that I better understand the `$` syntax's behavior, I can see that in a number of places, we are subscribing to updates when they are not relevant. Most of these are for the recipient names, which don't change after the initial flow.
This change reduces the number of subscriptions, which should have the effect of reducing some CPU from callbacks. It's probably minimal, but at least it's a little cleaner.

Use the recipient store less frequently

---

src/routes/guides/1st-and-2nd-of-month/+page.svelte
src/routes/guides/covid-awi-drop/+page.svelte
src/routes/guides/delayed-january-bump/+page.svelte
src/routes/guides/earnings-cap/+page.svelte
src/routes/guides/earnings-record-paste/+page.svelte
src/routes/guides/federal-taxes/+page.svelte
src/routes/guides/filing-date-chart/+page.svelte
src/routes/guides/guide.css
src/routes/guides/indexing-factors/+page.svelte
src/routes/guides/inflation/+page.svelte
src/routes/guides/international-agreements/+page.svelte
src/routes/guides/maximum/+page.svelte
src/routes/guides/spousal-benefit-filing-date/+page.svelte
src/routes/guides/will-social-security-run-out/+page.svelte
svelte.config.js

Guide CSS was sticking around if the user navigated to another page. Preprocessing the guides fixes this issue.
Fixes https://github.com/Gregable/social-security-tools/issues/297

Fix CSS for guides.

---

src/lib/pia.ts

If a recipient turned 62 in the current year, no COLA should be applied yet, since the COLA is applied in January of the following year.
However, when the COLA adjustment is known in October, we can still show the COLA adjustment to those 62 year old recipients who will in fact be eligible for the COLA in January but we were not doing so.

Bug Fix for COLA of recipient currenly 62 years.

---

src/lib/components/IndexedEarningsReport.svelte

The cutoff value for earnings was not reacting to changes to the future earnigns slider.

Fix reactivity issue with IndexedEarningsReport.

---

src/lib/components/FutureEarningsSliders.svelte
src/lib/constants.ts
src/lib/recipient.ts

If we know the maximum earnings for a future year, which happens late in the current year, allow the future wage slider to go up to that new value.
This also enforces capping future earnings wages to the maximum earnings for that year, if present. The result is that even if a user sets the slider to a value higher than the maximum earnings for the current year, the value will still be capped to the maximum earnings for that year.

Fixes #306

---

vercel.json

To use SharedArrayBuffer, we must emit the following headers:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```
Vercel is not emitting these headers in production. This commit adds a `vercel.json` file to the root of the project, as per instructions here:
https://vercel.com/guides/fix-shared-array-buffer-not-defined-nextjs-react

Attempt to get vercel to emit correct headers.

---

src/routes/guides/+layout.svelte

Makes things a little less cramped on mobile.

Add tiny padding to the guide layout.

---

src/lib/components/SurvivorReport.svelte

The date at which the survivor filed was capped at 66 in the slider, instead of set to their normal survivor retirement age. For those born late enough that this is 67, the slider wouldn't allow them to set the age high enough.

Quick fix for the survivor report

---

src/routes/strategy/+page.svelte
src/routes/strategy/components/RecipientInputs.svelte

- Add a scroll hint that appears when the calculation is complete, guiding the user to the results.
- Implement automatic scrolling to the strategy matrix display once the calculation finishes.
- Refine the "Recipient Information" section by adding "Primary Insurance Amount (PIA)" to the label for clarity.
- Adjust padding and margins for better visual presentation.

feat: Improve strategy page UX and add scroll hint
